# This is a basic workflow to help you get started with Actions

name: Oketo Deployment

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Okteto Login
      
        uses: okteto/login@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
